name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      
      - name: Build binaries
        run: |
          # macOS amd64
          GOOS=darwin GOARCH=amd64 go build -o voice-notify-mcp-darwin-amd64 .
          tar -czf voice-notify-mcp-darwin-amd64.tar.gz voice-notify-mcp-darwin-amd64
          
          # macOS arm64
          GOOS=darwin GOARCH=arm64 go build -o voice-notify-mcp-darwin-arm64 .
          tar -czf voice-notify-mcp-darwin-arm64.tar.gz voice-notify-mcp-darwin-arm64
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            voice-notify-mcp-darwin-amd64.tar.gz
            voice-notify-mcp-darwin-arm64.tar.gz
          generate_release_notes: true